### ISSUE TITLE
Fail to compile on ubuntu 21.10

### ISSUE THREAD

**Issue by ecohanim** [Maiqel/TP-Link-Archer-T4U-AC1300-Linux-driver-kernel-55#3]
System Info
=========
cat /proc/version:
(gcc (Ubuntu 11.2.0-7ubuntu2) 11.2.0

uname -r:
kernel version: 5.13.0-22-generic

gcc -v:
gcc version 11.2.0 (Ubuntu 11.2.0-7ubuntu2)

Failure reason
===========
/home/user/Downloads/TP-Link-Archer-T4U-AC1300-Linux-driver-kernel-55-master/os_dep/linux/recv_linux.c: In function ‘napi_recv’:
/home/user/Downloads/TP-Link-Archer-T4U-AC1300-Linux-driver-kernel-55-master/os_dep/linux/recv_linux.c:357:76: error: ‘GRO_DROP’ undeclared (first use in this function)
  357 |                         if (rtw_napi_gro_receive(&padapter->napi, pskb) != GRO_DROP)
      |                                                                            ^~~~~~~~
/home/user/Downloads/TP-Link-Archer-T4U-AC1300-Linux-driver-kernel-55-master/os_dep/linux/recv_linux.c:357:76: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [scripts/Makefile.build:281: /home/user/Downloads/TP-Link-Archer-T4U-AC1300-Linux-driver-kernel-55-master/os_dep/linux/recv_linux.o] Error 1
make[1]: *** [Makefile:1879: /home/user/Downloads/TP-Link-Archer-T4U-AC1300-Linux-driver-kernel-55-master] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.13.0-22-generic'
make: *** [Makefile:1999: modules] Error 2

**Comment by Maiqel** [comment]
Hello @ecohanim 
Please check now. I found piece of code that should resolve this issue, but I don't have setup for needed compilation. Please share your feedback if this works!
Best regards,
Maiqel
